#! /usr/bin/ruby

require 'fileutils'

SOFTWARE_VERSIONS = {}


def set_software_versions
  ARGV.map { |arg| arg.split("=") }.to_h.merge(SOFTWARE_VERSIONS)
end

def install_homebrew
  system_calls "/usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
end


def install_homebrew_packages
  system_calls "brew install #{brew_packages}"
end


def set_up_rbenv
  system_calls(
    "rbenv init",
    "rbenv install #{SOFTWARE_VERSIONS[:ruby]}",
    "rbenv global #{SOFTWARE_VERSIONS[:ruby]}",
    "gem install bundler",
    "rbenv rehash"
  )
end

def set_up_nvm
  home_dir = Dir.home
  bash_profile = "#{home_dir}/.bash_profile"
  FileUtils.touch(bash_profile) unless File.exist?(bash_profile) # required for nvm script to work
  system_calls "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash"

  set_up_nodejs
end

def set_up_nodejs
  node_version = SOFTWARE_VERSIONS[:node] || 'node'

  system_calls(
    "nvm install #{node_version}",
    "nvm alias default #{node_version}"
  )
end


def system_calls(*calls)
  exec_call = -> (call) do
    begin
      system call
    rescue => error
      puts error
    end
  end

  calls.each(&exec_call)
end


def brew_packages
  File.readlines('./brew_formulae.txt')
  .map { |line| line.gsub(/\n/, ' ') }
  .inject(&:+)
end

set_software_versions
install_homebrew
install_homebrew_packages
set_up_rbenv
set_up_nvm
